### ISSUE TITLE
Parse the exported memory file

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/comet_tools#8]
We need to parse the exported memory file into elinks. The parsing code is located in `GbtxMemParser.py`.

In that file, there's a class with three methods, and I have specified both input and output of each method in its `__doc__`.

**Comment by LegyPlegy** [comment]
one row of the memory file. written with indices to aid my counting

0 8
1 0
2 0
3 C
4 F
5 F
6 F
7 5
8 F
9 F
10 F
11 F
12 4
13 1
14 F
15 F
16 F
17 F
18 F
19 F
20 F
21 F
22 F
23 F
24 F
25 F
26 0
27 0
28 0
29 0
30 0
31 0

indices 0-3 are header, then (4,5), (6,7)... are each one byte. in the example above, (4,5) -> FF, (6,7) -> F5, (8,9) -> FF, etc. Note the form is (even, odd)

**Comment by LegyPlegy** [comment]
One example line of from the memory file written as a python list of tuples.
```
[('8', '0'), ('0', 'C'), ('F', 'F'), ('D', '7'), ('F', 'F'), ('F', 'F'), ('2', '0'), ('F', 'F'), ('F', 'F'), ('F', 'F'), ('F', 'F'), ('F', 'F'), ('F', 'F'), ('0', '0'), ('0', '0'), ('0', '0')]
```
If I understand the [wiki](https://github.com/umd-lhcb/lab-notes/wiki/GBTx-widebus-dataframe-explained) correctly, then each tuple in the above list corresponds to a single **elink**, meaning there are 14 elinks, and there are 7 **egroups**, where each egroup consists of 2 elinks.

If that is the case then the comments in GbtxMemParser are slightly misleading, since they say there are only 7 elinks.

my current approach is to use tuples to represent a single egroup, where the bytes have been converted from hex to int. 

Then our dictionary can look like this
```
default = (245, 95)  # placeholder - (245,95) = (F5, 5F)
egroup_dict = {       # sample egroup_dict, dummy value s
                'egroup0': default,
                'egroup1': default,
                'egroup2': default,
                'egroup3': default,
                'egroup4': default,
                'egroup5': default,
                'egroup6': default
                 }  
```

so egroup0 would have (elink1, elink2), where elink1 is just an integer. egroup2 would have (elink3, elink4).

I believe this would be more manageable and intuitive than to have elink0-0, elink0-1, elink1-0, elink1-1 as separate keys in the dictionary, especially since I think we're going to have to create a for loop that manually assigns each dictionary key on a string-by-string basis. Looping through each bit in each line in the memory file seems to be impossible.

**Comment by yipengsun** [comment]
Separating `egroups`, instead of `elinks`, was my initial idea as well. However, I realized that it is necessary to separate into `elinks` to perform subsequent error checks. That's why we need to separate into `elinks`.

**Comment by yipengsun** [comment]
Also, in `GbtxMemParser.py`, the comment says `Egroup ordering...`, which is correct. But I agree that we should be more explicit about `elink`.

**Comment by LegyPlegy** [comment]
Using the example memory line:
`800C | FF | 7D | FF | FF | 5C | FF | FF | FF | FF | FF | FF | 00 | 00 | 00 `
we can see that the memory lines follow the convention:
` header | 6-0 | 6-1 | 5-0 | 5-1 | 4-0 | 4-1 | 3-0 | 3-1 | 2-0 | 2-1 | 1-0 | 1-1 | 0-0 | 0-1 `

The table on the bottom right lists the elink and its corresponding index on the string "string_of_hexes". "string_of_hexes" has stripped out the header, and thus has the format:
` | 6-0 | 6-1 | 5-0 | 5-1 | 4-0 | 4-1 | 3-0 | 3-1 | 2-0 | 2-1 | 1-0 | 1-1 | 0-0 | 0-1 `

Seeing that elink `x-y` corresponds to list index `z`, we see that the formula to convert `x-y` to `z` is 

`2*(6-x) + y`

which is valid only for the given string "string_of_hexes".

Ignore the table on the bottom left, I used it to organize my thoughts.

![IMG_1136](https://user-images.githubusercontent.com/40072973/54934383-cbd17780-4ef4-11e9-926d-7e66ec589cc3.jpg)

**Comment by yipengsun** [comment]
I have merged your branch to `master` and deleted the `jorge` branch. If you want to do anything new, please recreate `jorge` based on current `master`.
